version: '3'

services:
  logstash:
    hostname: logstash
    image: ws/logstash:6.5.2
    container_name: logstash
    build:
      context: logstash
      dockerfile: Dockerfile
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      LOG_LEVEL: info
    ports:
      - 5044:5044
    links:
      - elasticsearch
      
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:7.17.3
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    links:
      - kibana
      
  kibana:
    hostname: kibana
    image: kibana:7.17.3
    container_name: kibana
    environment:
      - "LOGGING_QUIET=true"
      - "ELASTICSEARCH_URL=http://192.168.1.8:9200"
      - "ELASTICSEARCH_HOSTS=http://192.168.1.8:9200"
    ports:
      - 5601:5601
